# Generated by Django 4.1 on 2025-06-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('idproyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nomproyecto', models.CharField(max_length=100)),
                ('tiempo', models.TimeField()),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
            ],
        ),
    ]
